"""add unique constraint to source_event_id

Revision ID: 027860447804
Revises: 8f951708f9c4
Create Date: 2026-02-12 13:01:33.239494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027860447804'
down_revision = '8f951708f9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['source_event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
