"""add net_correct and accuracy

Revision ID: cd5324385e06
Revises: 676fc9a40177
Create Date: 2026-02-13 16:54:57.044191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5324385e06'
down_revision = '676fc9a40177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_correct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_scores', schema=None) as batch_op:
        batch_op.drop_column('accuracy')
        batch_op.drop_column('net_correct')

    # ### end Alembic commands ###
