"""add duplicate_of_attempt_id to attempts

Revision ID: d6302f35abbb
Revises: 79fcf89c2d63
Create Date: 2026-02-11 22:40:46.979945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6302f35abbb'
down_revision = '79fcf89c2d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_attempt_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'attempts', ['duplicate_of_attempt_id'], ['id'])
        batch_op.drop_column('started_at')
        batch_op.drop_column('answers')
        batch_op.drop_column('source_event_id')
        batch_op.drop_column('raw_payload')
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source_event_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duplicate_of_attempt_id')

    # ### end Alembic commands ###
